export const basicList: string[] = [
	'control your local water treatment plant',
	'choose targets to drone strike',
	'control the traffic lights',
	'write your job applications',
	'choose which candidate to hire',
	'deicide your salary',
	'write a Birthday card to your coworker ',
	'write a Thank You letter to your grandmother',
	'track and manage your day to day health',
	'diagnose that weird mole on your back',
	'summarise a book you want to read',
	'give you therapy for your crippling depression',
	'curate the music you listen to',
	'ghost-write for your favourite artist',
	'create a new netflic show',
	'drive your child to school',
	'choose what you have for dinner',
	'take your order at your favourite restaurant ',
	'find you a date',
	'curate your dating profile',
	'give your orgasms',
	'give you relationship advice',
	'write your best man speech',
	'break up with someone you dated for month',
	'break up with someone you dated for years',
	'referee your favourite sport',
	'keep in touch with your friends',
	'teach your Philosophy of Technology class',
	'teach you how to fix your leaky washing machine',
	'teach your child to cycle',
	'summarise an email from your boss',
	'summarise your friends group chat',
	'vote for you in your local election',
	'choose who gets a visa',
	'write your master’s thesis',
	'grade your final exam',
	'manage your finances',
	"be your bank's customer support",
	'plan your next family holiday',
	'drive your Uber',
	'write your diary',
	'remember all the conversations you had a house party',
	'be your nurse in hospital',
	'write the daily news',
	'create videos for your children to watch',
	'choose if the plice can stop and search you',
	'decide when you can get parole',
	'pacify your child on a long plane journey',
	'write your grant application',
	'choose who to give grants to',
	'write your protest banners',
	'be your romantic partner',
	'be your friend',
	'design new protein structures',
	'design new more efficient transport',
	'code your new website',
	'make your holiday photos more picturesque',
	'spell and grammer check this website',
	'translate the language of your partner',
	'write a legal letter to dispute your parking ticket',
	'write a booker prize winning book'
];
